import { mkdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'

const required = [
  'FIXTURE_DIR',
  'PACKAGE_NAME',
  'PACKAGE_VERSION',
  'REGISTRY',
]

for (const name of required) {
  if (!process.env[name]) {
    throw new Error(`${name} is required`)
  }
}

const fixtureDir = path.resolve(process.env.FIXTURE_DIR)
const manifest = {
  name: process.env.PACKAGE_NAME,
  version: process.env.PACKAGE_VERSION,
  description: 'Temporary package generated by the npm OIDC public smoke test',
  license: 'MIT',
  files: [
    'index.js',
  ],
  publishConfig: {
    access: 'public',
    registry: process.env.REGISTRY,
  },
}

if (process.env.GITHUB_REPOSITORY && process.env.GITHUB_REPOSITORY !== 'false') {
  manifest.repository = {
    type: 'git',
    url: `https://github.com/${process.env.GITHUB_REPOSITORY}.git`,
  }
}

await rm(fixtureDir, { force: true, recursive: true })
await mkdir(fixtureDir, { recursive: true })
await writeFile(
  path.join(fixtureDir, 'package.json'),
  `${JSON.stringify(manifest, null, 2)}\n`
)
await writeFile(
  path.join(fixtureDir, 'index.js'),
  'module.exports = {}\n'
)
